//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace assignments.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee
    {
        public employee()
        {
            this.requests = new HashSet<request>();
            this.requests1 = new HashSet<request>();
        }
    
        public int e_id { get; set; }
        public string e_name { get; set; }
        public string e_address { get; set; }
    
        public virtual ICollection<request> requests { get; set; }
        public virtual ICollection<request> requests1 { get; set; }
    }
}
