//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace assignments.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class food
    {
        public int f_id { get; set; }
        public string f_name { get; set; }
        public int req_id { get; set; }
    
        public virtual request request { get; set; }
    }
}
