//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace assignments.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class request
    {
        public request()
        {
            this.foods = new HashSet<food>();
        }
    
        public int req_id { get; set; }
        public int r_id { get; set; }
        public Nullable<int> collected_by { get; set; }
        public Nullable<int> dis_by { get; set; }
        public System.TimeSpan preserve_time { get; set; }
        public string status { get; set; }
    
        public virtual employee employee { get; set; }
        public virtual employee employee1 { get; set; }
        public virtual ICollection<food> foods { get; set; }
        public virtual restaurant restaurant { get; set; }
    }
}
