//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace assignments.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class restaurant
    {
        public restaurant()
        {
            this.requests = new HashSet<request>();
        }
    
        public int r_id { get; set; }
        public string r_name { get; set; }
        public string r_address { get; set; }
    
        public virtual ICollection<request> requests { get; set; }
    }
}
